# ENDPOINTS - CONNECT API

@baseUrl = http://localhost:5000

### AUTENTICAÇÂO - CRIAR SENHA
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
 "email": "lauanderson38@gmail.com",
 "senha": "minha_senha_secreta"
}

### AUTENTICAÇÂO - LOGIN
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
 "email": "participante@email.com",
 "senha": "minha_senha_secreta"
}

### PROGRAMAÇÃO - LISTAR PALESTRAS
GET {{baseUrl}}/api/v1/palestras

### PROGRAMAÇÃO - FILTRAR PALESTRAS
GET {{baseUrl}}/api/v1/palestras?tipo=Workshop

### PARTICIPANTES - LISTAR TODOS USUARIOS
GET {{baseUrl}}/api/v1/usuarios

### QR CODE - REGISTRAR PRESENÇA
POST {{baseUrl}}/api/v1/presenca
Content-Type: application/json

{
    "participanteId": "69266189a9e74a0fc2694e60",
    "palestraId": "6926618aa9e74a0fc2694e63"
}

### QR CODE - LISTAR PRESENÇAS - Com o id do participante
# GET {{baseUrl}}/api/v1/presenca/{participanteId}
GET {{baseUrl}}/api/v1/presenca/69266189a9e74a0fc2694e61

### SORTEIO - ÚNICO ENDPOINT (resumo + detalhes + filtros)
POST {{baseUrl}}/api/v1/sorteio/usuarios/all
Content-Type: application/json

{
  "minFeedbacks": 0,
  "minVotos": 0,
  "minPresencas": 0,
  "minQuizScore": 0
}
